# -*- coding: utf-8 -*-
"""
Created on Mon Jun 19 23:05:58 2023

@author: User
"""
import streamlit as st
from joblib import load
import pandas as pd
import altair as alt

# title of Streamlit application
st.title("Prediction of global terrorist attacks")

# Load the model
model = load("model.joblib")

session = st.session_state

if "region_name" not in session:
    session.region_name = "Australasia & Oceania"
if "country_name" not in session:
    session.country_name = "Australia"
if "country_options" not in session:
    session.country_options = []
if "city_options" not in session:
    session.city_options = []
if "group_options" not in session:
    session.group_options = []


def set_country_option(region):
    if region == "Australasia & Oceania":
        session.country_options = [
            "Australia",
            "Papua New Guinea",
            "New Caledonia",
            "New Zealand",
            "Fiji",
            "French Polynesia",
            "Solomon Islands",
            "Wallis and Futuna",
            "New Hebrides",
        ]
    elif region == "Middle East & North Africa":
        session.country_options = [
            "Iraq",
            "Turkey",
            "Yemen",
            "Algeria",
            "Lebanon",
            "Egypt",
            "Libya",
            "West Bank and Gaza Strip",
            "Israel",
            "Syria",
            "Iran",
            "Saudi Arabia",
            "Bahrain",
            "Tunisia",
            "Jordan",
            "Kuwait",
            "Morocco",
            "United Arab Emirates",
            "North Yemen",
            "Western Sahara",
            "Qatar",
        ]
    elif region == "Sub-Saharan Africa":
        session.country_options = [
            "Angola",
            "Benin",
            "Botswana",
            "Burkina Faso",
            "Burundi",
            "Cameroon",
            "Central African Republic",
            "Chad",
            "Comoros",
            "Democratic Republic of the Congo",
            "Djibouti",
            "Equatorial Guinea",
            "Eritrea",
            "Ethiopia",
            "Gabon",
            "Gambia",
            "Ghana",
            "Guinea",
            "Guinea-Bissau",
            "Ivory Coast",
            "Kenya",
            "Lesotho",
            "Liberia",
            "Madagascar",
            "Malawi",
            "Mali",
            "Mauritania",
            "Mozambique",
            "Namibia",
            "Niger",
            "Nigeria",
            "People's Republic of the Congo",
            "Republic of the Congo",
            "Rhodesia",
            "Rwanda",
            "Senegal",
            "Seychelles",
            "Sierra Leone",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Sudan",
            "Swaziland",
            "Tanzania",
            "Togo",
            "Uganda",
            "Zaire",
            "Zambia",
            "Zimbabwe",
        ]
    else:
        session.country_options = ["NOT IMPLEMENTED"]


def set_city__group_option(country):
    if country == "Australia":
        session.city_options = [
            "Adelaide",
            "Beechworth",
            "Brighton",
            "Brisbane",
            "Broadbeach",
            "Canberra",
            "Condell Park",
            "Dandenong",
            "Fawkner",
            "Geelong",
            "Kakudu National Park",
            "Liverpool",
            "Melbourne",
            "Norlane",
            "Normahurst",
            "Oberon",
            "Orange",
            "Parramatta",
            "Perth",
            "Queanbeyan",
            "Rooty Hill",
            "St. Kilda East",
            "Sydney",
            "Townsville",
            "Unknown",
            "Waitara",
        ]
        session.group_options = [
            "Animal Liberation Front (ALF)",
            "Anti-Nuclear extremists",
            "Black September",
            "Croatian Nationalists",
            "Extortionists",
            "Greek Bulgarian Armenian Front",
            "Informal Anarchist Federation",
            "Islamic State of Iraq and the Levant (ISIL)",
            "Jihadi-inspired extremists",
            "Kurds",
            "Neo-Nazi extremists",
            "U/I Asian Gang",
            "Unknown",
        ]
    elif country == "Iraq":
        session.city_options = [
            "Aalos",
            "Abar Sadiyah",
            "Abasiyah",
            "Abbarah",
            "Abbasi",
            "Abdul Karim",
            "Abkaziyah",
            "Abrah Aziz",
            "Abu Al Khasib",
            "Abu Al-Khasib",
            "Abu Bushut",
            "Abu Darujah",
            "Abu Fleis",
            "Abu Gharah",
            "Abu Ghraib",
            "Abu Ghraib district",
            "Abu Jair",
            "Abu Jaradi",
            "Abu Karmah",
            "Abu Khamis",
            "Abu Khanazir",
            "Abu Khashab",
            "Abu Sanam",
            "Abu Sayda",
            "Abu Saydah",
            "Abu Tabah",
            "Abu al Khasib district",
            "Abu al-Duhan",
            "Abu al-Khasib",
            "Ad Dawasah",
            "Ad Dibs district",
            "Adayah",
            "Adhaim",
            "Adnaniyah",
            "Afak",
            "Ain Fathi",
            "Ain al-Jahash",
            "Ain al-Naml",
            "Ain al-Tamur district",
            "Ajbalah",
            "Ajeem",
            "Ajhalah",
            "Akarkouf",
            "Akashat",
            "Akba",
            "Akla",
            "Akre",
            "Al Busleibi",
            "Al Jibour",
            "Al-Abbarah",
            "Al-Abbasi",
            "Al-Abd",
            "Al-Adheim",
            "Al-Ahnaf village",
            "Al-Alam",
            "Al-Arbaj",
            "Al-Arifiyah",
            "Al-Asiri",
            "Al-Askari",
            "Al-Asoud",
            "Al-Asriyah",
            "Al-Aswad",
            "Al-Atshanah",
            "Al-Awamer",
            "Al-Awaser",
            "Al-Ayadieh",
            "Al-Azrakiyah",
            "Al-Ba'aj",
            "Al-Baghdadi",
            "Al-Bah",
            "Al-Barhiyah",
            "Al-Basiyah",
            "Al-Bazul",
            "Al-Dalouiya",
            "Al-Dubat",
            "Al-Dulaya",
            "Al-Dur district",
            "Al-Falahat",
            "Al-Faris district",
            "Al-Fathah",
            "Al-Fhilat",
            "Al-Furat",
            "Al-Ghalibiyah",
            "Al-Hadid",
            "Al-Hajj",
            "Al-Hajjaj",
            "Al-Halabisah",
            "Al-Hamamiyat",
            "Al-Hamra",
            "Al-Hanshi",
            "Al-Hashimiya area",
            "Al-Hashimiyah",
            "Al-Hassan",
            "Al-Hauz",
            "Al-Hawija",
            "Al-Hayakil",
            "Al-Hayy Al-Askari",
            "Al-Hitawiyin",
            "Al-Humairat",
            "Al-Hussainiyah",
            "Al-Husseiniya",
            "Al-Imam district",
            "Al-Islah",
            "Al-Iyadhiyah",
            "Al-Jari",
            "Al-Jazirah",
            "Al-Jughayfi",
            "Al-Karama",
            "Al-Kazimiyah",
            "Al-Khabbaz",
            "Al-Khadraniyah",
            "Al-Khalisah",
            "Al-Khasfah",
            "Al-Kifl",
            "Al-Kissik area",
            "Al-Kubayshat",
            "Al-Kuthahiyah",
            "Al-Layn",
            "Al-Lazakah",
            "Al-Madiq",
            "Al-Malihah",
            "Al-Mansuriyah",
            "Al-Mazari",
            "Al-Mishahida",
            "Al-Muaibidi",
            "Al-Mukhaysah",
            "Al-Murra Al-Kobra",
            "Al-Mutasim",
            "Al-Nahrawan",
            "Al-Nasr",
            "Al-Obeidi",
            "Al-Qadisiyah",
            "Al-Qarraj",
            "Al-Qaws",
            "Al-Quds",
            "Al-Rakah",
            "Al-Rashad",
            "Al-Ray",
            "Al-Rayash",
            "Al-Riyad",
            "Al-Rubeida",
            "Al-Saadiyh",
            "Al-Sadan",
            "Al-Salam",
            "Al-Sgelh",
            "Al-Shieha",
            "Al-Sifr",
            "Al-Siniyah",
            "Al-Suweira district",
            "Al-Tahrir area",
            "Al-Tin",
            "Al-Urayj",
            "Al-Walib",
            "Al-Wardiyah",
            "Al-Wind",
            "Al-Zaidan",
            "Al-Zawiyah",
            "Al-Zubair district",
            "Al-\x91Ayth",
            "Alam",
            "Albohushma",
            "Albu Ajil",
            "Albu Ali",
            "Albu Alwan",
            "Albu Assaf",
            "Albu Awad",
            "Albu Awsaj",
            "Albu Ayfan",
            "Albu Aythah",
            "Albu Bahani",
            "Albu Bakr",
            "Albu Bali",
            "Albu Dhiyab",
            "Albu Diab",
            "Albu Faraj",
            "Albu Ghanim",
            "Albu Hamad",
            "Albu Hasan",
            "Albu Hawa",
            "Albu Hawah",
            "Albu Hayat",
            "Albu Jumah",
            "Albu Khado",
            "Albu Khadu",
            "Albu Khalifah",
            "Albu Khanfar",
            "Albu Mufarrij",
            "Albu Muhammad",
            "Albu Musa",
            "Albu Nemir",
            "Albu Obaid",
            "Albu Rishah",
            "Albu Sayf",
            "Albu Shehab",
            "Albu Shejel",
            "Albu Souda",
            "Albu Tumah",
            "Albu Ubayd",
            "Albu-Hashmah",
            "Albu-Khaddu",
            "Alexandria",
            "Alhmeirah",
            "Ali Al-Ghir",
            "Ali Farhan",
            "Aliser",
            "Almas",
            "Altun Kupri",
            "Amadiyah",
            "Amarah",
            "Amarliya",
            "Amerli",
            "Amianuk district",
            "Amiriyah",
            "Amiriyat Al-Fallujah",
            "Amiriyat al-Fallujah",
            "Amiriyat al-Samoud",
            "Amriyat al-Fallujah",
            "Anah",
            "Anaz",
            "Anbakiya",
            "Anjanah",
            "Ankawah",
            "Ar Radwaniyah",
            "Ar Rashidiyah",
            "Arab Albu Dhiyab",
            "Arab Jabour",
            "Arab Jasim",
            "Arab Nuri",
            "Arab Thauailib",
            "Arab al-Haytawiyin",
            "Arab ar Rawashid",
            "Arbil",
            "Arej",
            "Arifiyah",
            "As Sabah Kilu",
            "As Sadid",
            "As Sakran",
            "As Salabikhah",
            "As Salam",
            "As Sawaid",
            "As Sayad",
            "As Siniyah",
            "As Suwayrah district",
            "As-Saadiyah",
            "Asasirah",
            "Ash Shamsiyah",
            "Ash Sharif Abbas",
            "Ash Sharifiyah",
            "Ash Shaykh Ahmad",
            "Ashraf",
            "Askari",
            "Aski",
            "Aski Mosul",
            "Asriyah",
            "Asyud",
            "Athba",
            "Athiya",
            "Awdat al-Shukr",
            "Awjah",
            "Ayn al-Baydah",
            "Ayn al-Hisyan",
            "Aythah",
            "Az-Zab",
            "Azim",
            "Aziziyah",
            "Baaj",
            "Baashiqah",
            "Bab al-Sham",
            "Babil",
            "Babilan",
            "Badush",
            "Baghdad",
            "Baghdad district",
            "Bahbahan",
            "Bahzar",
            "Baiji",
            "Baiji district",
            "Bajawan",
            "Bakriyah",
            "Balad",
            "Balad Ruz",
            "Balad Ruz district",
            "Balad district",
            "Bani Saad",
            "Bani Saad district",
            "Baquba",
            "Baquba district",
            "Baqubah",
            "Baqubah district",
            "Bartella",
            "Bartella district",
            "Barwana",
            "Barwanat al-Kabira",
            "Bashiqa",
            "Bashiqah",
            "Bashir",
            "Bashmanah",
            "Bashmaya",
            "Basmaya",
            "Basmayah",
            "Basra",
            "Basra district",
            "Bastamly",
            "Bawi",
            "Bawiyah",
            "Bawizah",
            "Bay Hasan",
            "Bazayez",
            "Bikr",
            "Bir Ahmad",
            "Bir Ahmed",
            "Bishkan",
            "Bismaya",
            "Bohruz",
            "Border",
            "Brawchi",
            "Bruwana al-Kabira",
            "Bub Ash Sham",
            "Bubali",
            "Budijah",
            "Buhardan",
            "Buhriz",
            "Buhriz district",
            "Buwayr",
            "Chamchamal",
            "Chechi",
            "Cheman",
            "Choman district",
            "Dabaa",
            "Dagharah",
            "Dalim",
            "Dalli Abbas",
            "Daquq",
            "Daquq district",
            "Darbas",
            "Dariyah",
            "Dawalib",
            "Dawiyah",
            "Dawr",
            "Dawr district",
            "Dawreh",
            "Dayr",
            "Dayum",
            "Delli Abbas",
            "Deraa Dijla",
            "Dhi Qar",
            "Dhuluiya",
            "Dibis",
            "Dibis district",
            "Dijlah",
            "Dira Dijlah",
            "Diriyah",
            "Diwaniyah",
            "Diyana",
            "Dojamah",
            "Dokan",
            "Domiz",
            "Dore",
            "Dowr",
            "Duhok",
            "Dujail",
            "Dujail district",
            "Dujaila district",
            "Dukhlah",
            "Dulab",
            "Duluiyah",
            "Dumez Sinjar",
            "Dur ar-Rifaq",
            "Dur as Safra",
            "Dura Mandali",
            "Duwailiya",
            "Duwayzat",
            "Edheim",
            "Falahat",
            "Fallujah",
            "Fallujah district",
            "Farhan",
            "Farhatiyah",
            "Farisiyah",
            "Faruq",
            "Fathah",
            "Faw",
            "Faysaliyah",
            "Furat",
            "Ganaveh",
            "Gayara",
            "Gelyuhan",
            "Ghalibiyah",
            "Gharaf",
            "Gharib",
            "Ghazail",
            "Ghudayb",
            "Habbaniyah",
            "Habhab",
            "Had Akhdar",
            "Hadar",
            "Hadba",
            "Hadhar",
            "Hadid",
            "Haditha district",
            "Hadithah",
            "Hadithah district",
            "Hadra",
            "Hafriyah",
            "Hajaf",
            "Hajjaj",
            "Hajlah",
            "Hakim district",
            "Hakna",
            "Halabisah",
            "Halabjah",
            "Halabsah",
            "Halaiwat",
            "Halyawa",
            "Hamamiyah",
            "Hamamiyat",
            "Hamayel",
            "Hamdaniyah",
            "Hamdaniyah district",
            "Hamel",
            "Hamidhiyah",
            "Hammam al-Alil",
            "Hamra",
            "Hamrah",
            "Hamza Al-Gharbi",
            "Hanbas",
            "Haot",
            "Haqlaniyah",
            "Harariyat",
            "Hardan",
            "Harijiyah",
            "Haruniyah district",
            "Hashimiyah",
            "Haswa",
            "Haswah",
            "Hatra",
            "Hatra district",
            "Hawad",
            "Hawana",
            "Hawash",
            "Hawd al-Waqf",
            "Hawijah",
            "Hawijah district",
            "Hawr Rajab",
            "Hawr Salah ad Din",
            "Hay Abu-Dashir",
            "Hay al-Iskan",
            "Hay al-Muasasah",
            "Hay al-Qadisiyah",
            "Hay al-Sinai",
            "Hayy An Nur",
            "Hayy Aqsu",
            "Hayy al-Askari",
            "Hayy al-Jamiah",
            "Hayy al-Jumhuri",
            "Hibhib",
            "Hillah",
            "Himreen",
            "Hindiyah",
            "Hit",
            "Hit district",
            "Hor al-Bashah",
            "Hud",
            "Hujir",
            "Hulaylah",
            "Hulaywah",
            "Huran",
            "Huriyah",
            "Husaybah",
            "Husayn",
            "Husseiniyah",
            "Huwaider",
            "Huwaydir",
            "Huwaysh",
            "Hwaish",
            "Ibrahim Ali",
            "Imam Ahmad",
            "Imam Gharbi",
            "Imam Mansour",
            "Imam Wais",
            "Imam Ways",
            "Imam Weis",
            "Imam-Wais",
            "Injana",
            "Irbic",
            "Ishaqi",
            "Ishaqi district",
            "Iskandariyah",
            "Ismail Awa",
            "Itfa",
            "Jaarah",
            "Jabal al-Qayyarah",
            "Jabella",
            "Jablah",
            "Jabur",
            "Jadidah",
            "Jadidat ash Shatt",
            "Jalawla",
            "Jalawlah",
            "Jallam",
            "Jamahir",
            "Jamila",
            "Jamliya",
            "Jammasa",
            "Janjali",
            "Jarwana",
            "Jazirah",
            "Jbela",
            "Jeraishi",
            "Jilam",
            "Jisr Az Zarkah",
            "Jisr Diyala",
            "Jizani",
            "Jubah",
            "Jubur",
            "Jumasah",
            "Jurf Naddaf",
            "Jurf al-Sakhar",
            "Jurf al-Sakhar district",
            "Jurf al-Sakhr",
            "Jurn",
            "Juwaybah",
            "Kabah",
            "Kadila",
            "Kahrez",
            "Kalar District",
            "Kalkji",
            "Kan'an",
            "Kanaan",
            "Kanan",
            "Kanaos",
            "Kanazah",
            "Kara Teppa",
            "Karabilah",
            "Karaj",
            "Karamah",
            "Karanaz",
            "Karbala",
            "Karma",
            "Kashkul",
            "Kasik",
            "Kasr",
            "Katun",
            "Kazakan",
            "Kerja",
            "Kesnazan",
            "Khadra",
            "Khadraniyah",
            "Khalbishi",
            "Khalidiyah",
            "Khalis",
            "Khalis district",
            "Khammar",
            "Khan Bani Saad",
            "Khan Bani Saad district",
            "Khan Dari",
            "Khan Sur",
            "Khanaqin",
            "Khanaqin district",
            "Khanasah",
            "Khansa",
            "Khanukah",
            "Kharaib Jabr",
            "Kharar",
            "Kharbat Aziz",
            "Kharirdan",
            "Kharnabat",
            "Khazir",
            "Khidhir",
            "Khorsabad",
            "Khuitla",
            "Khurmal",
            "Kifil",
            "Kifri",
            "Kifri district",
            "Kilu Miat wa Sittin",
            "Kirkuk",
            "Kirkuk district",
            "Kiwan",
            "Kobashi",
            "Kolat",
            "Kraw",
            "Kuban",
            "Kubaysah",
            "Kubba",
            "Kufa",
            "Kurtan",
            "Kusaybah",
            "Kusayrin",
            "Kut",
            "Kut district",
            "Kuwayr",
            "Latifiyah",
            "Latifiyah district",
            "Laylan",
            "Lazaka",
            "Leine",
            "Lufat",
            "Maaskarat",
            "Madain",
            "Madain district",
            "Maftul",
            "Maftulah",
            "Mahalabiyah",
            "Mahanah",
            "Mahasinah",
            "Mahawil",
            "Mahawil district",
            "Mahdia",
            "Mahmudiyah",
            "Mahmudiyah district",
            "Mahus",
            "Mahwala",
            "Majidiyah",
            "Majjaj",
            "Makha",
            "Makhazin",
            "Makhmour",
            "Makhmur",
            "Makhmur district",
            "Makr al-Deeb",
            "Maktab Khalid",
            "Malahma",
            "Mama",
            "Manazlah",
            "Mandali",
            "Mansouriyah",
            "Mansuriyah",
            "Mansuriyat al Jabal",
            "Mara",
            "Mari",
            "Mariam Bek",
            "Marir",
            "Masayed",
            "Mashahda",
            "Mashahdah",
            "Mashahida",
            "Mashahidah",
            "Mashru",
            "Mawali",
            "Mayyah",
            "Mazra",
            "Mazrah",
            "Mela Omer",
            "Milhah",
            "Mirbusur",
            "Mishada",
            "Mishahda",
            "Mishraq",
            "Miyahi",
            "Mkeshiefa",
            "Mohammadi",
            "Mosul",
            "Mosul district",
            "Mowla",
            "Mueilha",
            "Muhallabiyah",
            "Muhayri",
            "Mujamaa al-Shahid",
            "Mukashafah",
            "Mukhaysah",
            "Mulla Jasim",
            "Mullah Abdullah",
            "Multaqa district",
            "Munirah",
            "Munshaat al-Muthanna",
            "Muqdadiyah",
            "Muqdadiyah district",
            "Muradiyah",
            "Musayib",
            "Musayyib",
            "Musayyib district",
            "Mushahadah",
            "Mushahidah",
            "Mushayrifah",
            "Muslakhah",
            "Mutawakiliyah",
            "Mutaybijah",
            "Muthanna",
            "Naft Khana",
            "Naft Khanah",
            "Nahr al-Imam",
            "Nahrawan",
            "Nahrwan",
            "Najaf",
            "Najaf-e Ashraf",
            "Naqshabandiyah",
            "Nasir",
            "Nasiriyah",
            "Nasiriyah district",
            "Nasr",
            "Nawafil",
            "Nazim Taqseem",
            "Nibaee",
            "Nibaie",
            "Nimrud",
            "Nineveh",
            "Nukhayb",
            "Numaniyah",
            "Nuran",
            "Obaidy",
            "Owainat",
            "Penjwin",
            "Penjwon",
            "Pirwajli",
            "Pirzeen",
            "Qadir Karam",
            "Qadisiyah",
            "Qaim",
            "Qaim district",
            "Qalah",
            "Qalat Dizah",
            "Qalat Duzzah",
            "Qamesh Tapa",
            "Qani",
            "Qara Durra",
            "Qara Tapa",
            "Qarah Tapah",
            "Qarah Tappah",
            "Qaraytagh",
            "Qarbat Albu Hayyat",
            "Qarghuliyah",
            "Qariyah Asriyah",
            "Qarrat Durrah",
            "Qaryat al-Bazul",
            "Qasim",
            "Qasreej",
            "Qawsiyat",
            "Qayarah",
            "Qayyarah",
            "Qayyarah district",
            "Qubah",
            "Qubbah",
            "Qurnah",
            "Rabia",
            "Rabiaa",
            "Rabiah",
            "Radhwaniyah",
            "Radwaniyah",
            "Rafaiyat",
            "Rahaliyah",
            "Rahmaniyah",
            "Ramadi",
            "Ramadi district",
            "Ranji",
            "Ranya",
            "Rashad",
            "Rashad district",
            "Rasheed",
            "Rasheed district",
            "Rashid",
            "Rashidiyah",
            "Rawah",
            "Rawfah",
            "Rawiyah",
            "Rayhanah",
            "Rifai district",
            "Riga",
            "Riyadh",
            "Riyadh district",
            "Rubaydah",
            "Rufush",
            "Rumaylah",
            "Rumaythah",
            "Rummana",
            "Rutba",
            "Rutbah",
            "Rutbah district",
            "Sab' Al Bor",
            "Saba al-Bor",
            "Sabbaghiyah",
            "Sabiat",
            "Sabunjiya",
            "Sadirah",
            "Sadiyah",
            "Sadiyah district",
            "Sadr al-Yusufiyah",
            "Saduniyah",
            "Saff at Tut",
            "Safinah",
            "Safra",
            "Sahaji",
            "Sahiliyah",
            "Sajariyah",
            "Sakrah",
            "Salamiyah",
            "Salehiya",
            "Salman Bak",
            "Samarra",
            "Samarra district",
            "Samawah",
            "Saniya",
            "Saqlawiah",
            "Saqlawiyah",
            "Sargaran",
            "Sarhah",
            "Sarkaran",
            "Sarsank",
            "Saslaj",
            "Satih",
            "Sayed Abdullah",
            "Sayed Ahmad",
            "Sayid Gharib",
            "Sayyid Abdullah",
            "Sedira",
            "Sejar",
            "Seven Nissan",
            "Shahraban",
            "Shajariyah",
            "Shakhat al Amiya",
            "Shakur",
            "Shamsiah",
            "Shaqufah",
            "Sharikhan",
            "Sharwain",
            "Sharwin",
            "Shaut",
            "Shawuk",
            "Shayyib",
            "Sheik Said",
            "Sheikh Hamad",
            "Sheikh Muhammad",
            "Shikhan",
            "Shirqat",
            "Shirqat district",
            "Shirween",
            "Shomali",
            "Shorah",
            "Shubayjah",
            "Shumayt",
            "Shura",
            "Sibaya",
            "Sidlan",
            "Sijalah",
            "Sindij",
            "Siniyah",
            "Sinjar",
            "Sinjar district",
            "Sinniah",
            "Sivi",
            "Soni",
            "Sor",
            "Suaydat",
            "Subaih",
            "Subayat",
            "Subayhat",
            "Sudur",
            "Sufiyah",
            "Sulayman Beg",
            "Sulaymaniyah",
            "Sultan Abdallah",
            "Sultan Abdullah",
            "Sumayr",
            "Suqur",
            "Sur Shanas",
            "Sura",
            "Sus",
            "Sutayh",
            "Suwaib",
            "Suwayrah",
            "Tabaj",
            "Tabbi Sar",
            "Tabi",
            "Taji",
            "Taji district",
            "Tajiyat",
            "Taklif",
            "Tal Abta",
            "Tal Abtah",
            "Tal Afar",
            "Tal Afar district",
            "Tal Al-Banat",
            "Tal Ali",
            "Tal Banat",
            "Tal Kayf",
            "Tal Masud",
            "Tal Saquf",
            "Tal Ubtta",
            "Tall Abtah",
            "Tall Ar Rim",
            "Tall Dhahab",
            "Tall Keysoum",
            "Tall Kusaybah",
            "Tall Maftul",
            "Tall Safouk",
            "Tall Zalat",
            "Tall al-Basal",
            "Tall al-Warad",
            "Tamemm",
            "Taq Taq",
            "Tariq",
            "Tarmiyah",
            "Tawakol",
            "Tawuq",
            "Taza Khurmatu",
            "Thalibah",
            "Tharthar",
            "Thiraa Dijla",
            "Tib district",
            "Tikrit",
            "Tikrit district",
            "Tilkef district",
            "Tirkit district",
            "Trebiel",
            "Tubzawah",
            "Tulkana",
            "Tullaiha",
            "Tulul al-Baj",
            "Turkulan",
            "Tuz Khormato",
            "Tuz Khormato district",
            "Tuz Khormatu district",
            "Twelha",
            "Udheim",
            "Um al-Sawn",
            "Umm Qasr",
            "Umran",
            "Unknown",
            "Uwayjah",
            "Uzaym",
            "Vaddahiyeh",
            "Verti",
            "Wadi Ghaydah",
            "Wadi Houran",
            "Wadi Iqab",
            "Wadi al-Ghadaf",
            "Wafa",
            "Wailiyah",
            "Wajihiyah",
            "Wajihiyah district",
            "Waleed",
            "Walid",
            "Walid Border Crossing",
            "Wanah",
            "Wardiyah",
            "Wasit",
            "Wasiti",
            "Wasti",
            "Watban",
            "Wihdah",
            "Wirdak",
            "Yankajah",
            "Yathrib",
            "Yatrhib",
            "Yayji",
            "Yethrib",
            "Yusufiyah",
            "Zab",
            "Zafaraniyah",
            "Zaganiah",
            "Zahrat Khatun",
            "Zaidan",
            "Zakho",
            "Zalaya",
            "Zalayah",
            "Zalhatah",
            "Zanazel",
            "Zanqurah",
            "Zarkah",
            "Zawiyah",
            "Zaydan",
            "Zeibat",
            "Zerga",
            "Zerge",
            "Zilkan",
            "Zinjili",
            "Zubaidiya",
            "Zubaidiyah",
            "Zubair",
            "Zubayr district",
            "Zuhayrat",
            "Zukhaykhah",
            "Zummar",
            "Zuriqi",
            "Zuwayyah",
        ]
        session.group_options = [
            "1920 Revolution Brigades",
            "Abu Nidal Organization (ANO)",
            "Al-Naqshabandiya Army",
            "Al-Nusrah Front",
            "Al-Qaida Kurdish Battalions (AQKB)",
            "Al-Qaida in Iraq",
            "Ansar al-Islam",
            "Ansar al-Jihad",
            "Ansar al-Sunna",
            "Armed Vanguards of a Second Mohammed Army",
            "Asa'ib Ahl al-Haqq",
            "Baathist extremists",
            "Badr Brigades",
            "Banner of Islam",
            "Barzani Guerrillas",
            "Brigades of Iman Hassan-al-Basri",
            "Death Squad (Iraq)",
            "Diyala Salvation Council",
            "Gunmen",
            "Hamawand Tribe",
            "Harakat al-Nujaba",
            "Imam Hussein Brigade",
            "Iraq's Jihadist Leagues",
            "Iraqi Islamic Vanguards for National Salvation (IIVNS)",
            "Iraqi Mujahideen",
            "Iraqi National Congress (INC)",
            "Iraqi Revolutionary Forces",
            "Iraqi extremists",
            "Islamic Army in Iraq (al-Jaish al-Islami fi al-Iraq)",
            "Islamic State of Iraq (ISI)",
            "Islamic State of Iraq and the Levant (ISIL)",
            "Jaish al-Ta'ifa al-Mansura",
            "Junaid Jihadist Battalion",
            "Jund Al-Tawid",
            "Jund al-Sahabah Group",
            "Just Punishment Brigades",
            "Kata'ib Hezbollah",
            "Kata'ib al-Imam Ali",
            "Khalid ibn Walid Brigade",
            "Kurdish Democratic Party-Iraq (KDP)",
            "Kurdish Militants",
            "Kurdistan National Union",
            "Kurdistan Workers' Party (PKK)",
            "Kurds",
            "Liberals of Galilee",
            "Mahdi Army",
            "Martyr Abu Ja'far Group",
            "Militants",
            "Military Council of the Tribal Revolutionaries (MCTR)",
            "Mujahedeen Army",
            "Mujahedeen Brigades",
            "Mujahedeen Corps in Iraq",
            "Mujahedeen Group",
            "Mujahedeen Shura Council",
            "Mujahedin-e Khalq (MEK)",
            "Mukhtar Army",
            "Munadil al-Jumalyi Brigade",
            "Muslim extremists",
            "Omar Bin Khattab Group",
            "Patriotic Union of Kurdistan (PUK)",
            "Popular Mobilization Forces (Iraq)",
            "Pro-Government extremists",
            "Protectors of Islam Brigade",
            "Revenge Brigade",
            "Salafi Abu-Bakr al-Siddiq Army",
            "Separatists",
            "Shia Muslim extremists",
            "Shield of Islam Brigade",
            "Sunni Muslim extremists",
            "Supreme Council for Islamic Revolution in Iraq (SCIRI)",
            "Tawhid and Jihad",
            "The Owners of the White Flags",
            "Tribesmen",
            "Unknown",
        ]
    elif country == "Nigeria":
        session.city_options = [
            "Aba",
            "Abaagu",
            "Abadam",
            "Abaji",
            "Abakaliki",
            "Abbari",
            "Abbati",
            "Abbi",
            "Abeokuta South district",
            "Abiam Koya",
            "Abiteye",
            "Abobo",
            "Abogbe",
            "Abonema",
            "Abonnema",
            "Abraka",
            "Abua-Odual district",
            "Abudu",
            "Abuja",
            "Abulagu",
            "Adagbo",
            "Adamu Agyo",
            "Adamu Agyo Fadama Buna",
            "Adavi district",
            "Adeka",
            "Ado Ekiti",
            "Ado-Ekiti",
            "Aduwari",
            "Afam Uku",
            "Afang",
            "Afao",
            "Afor-Igwe",
            "Agatu",
            "Agena",
            "Agrisaba",
            "Agunu",
            "Agwan Hamidu",
            "Agwan Mamman",
            "Agwatashi",
            "Aila",
            "Ajakpa",
            "Ajaokuta",
            "Ajiri",
            "Akalli",
            "Akepelai",
            "Akowonjo",
            "Akututuru district",
            "Akuzo",
            "Akwanga district",
            "Alaba",
            "Alakaramtii",
            "Alakyo",
            "Alau",
            "Alawa",
            "Alidawari",
            "Alkaleri",
            "Almeri",
            "Amarwa",
            "Amasomma",
            "Ambe Madaki",
            "Amber",
            "Amchaka",
            "Amorji Nike",
            "Amrawa",
            "Amuda",
            "Ananum",
            "Anawah",
            "Anchogo",
            "Angai",
            "Angwan Gata",
            "Angwan Sankwai",
            "Ankyov",
            "Anwen",
            "Anyiase",
            "Anyiin",
            "Arboko",
            "Aruogba",
            "Asaba",
            "Asemngoroko",
            "Ashaka",
            "Asham",
            "Ashigashiya",
            "Ashir",
            "Askira",
            "Askira Uba",
            "Assakio",
            "Atagara",
            "Atakar",
            "Atakwu",
            "Atta",
            "Attagara",
            "Attakar",
            "Auchi",
            "Audu",
            "Auno",
            "Awarra",
            "Awoba",
            "Awonguyo",
            "Awulari",
            "Ayiase",
            "Azare",
            "Azur",
            "Babban Gida",
            "Bachit",
            "Baga",
            "Bajoga",
            "Bakassi district",
            "Bakin Dutse",
            "Bakin Iku",
            "Bakin Kogi",
            "Bakun Allu",
            "Bakura district",
            "Balda",
            "Bali district",
            "Balile",
            "Bama",
            "Bama district",
            "Bangai",
            "Banki",
            "Bara",
            "Barakin Ladi",
            "Barkin Ladi district",
            "Batan",
            "Bauchi",
            "Bayan Gari",
            "Bazza",
            "Belgeri",
            "Beni Shiek",
            "Benin",
            "Benin City",
            "Benisheik",
            "Bera",
            "Birchi",
            "Birin Fulani",
            "Birnin Gwari district",
            "Birnin-Gwari",
            "Birniwa",
            "Bitiku",
            "Bitta",
            "Bittiku",
            "Bitu",
            "Biu",
            "Biu district",
            "Boftari",
            "Bomadi",
            "Bonny",
            "Bori",
            "Brass",
            "Bugama",
            "Bugda",
            "Buguma",
            "Bukuru",
            "Bulabulin",
            "Bulabulin Ngaura",
            "Bultaram",
            "Buma",
            "Bundaram",
            "Buni Yadi",
            "Bunkure",
            "Bununu",
            "Buraltuma",
            "Buratai",
            "Burga",
            "Buruku",
            "Buruto",
            "Calabar",
            "Chalawa",
            "Chibok",
            "Chibok district",
            "Chigama",
            "Chinene",
            "Cimari",
            "Dadin Kowa",
            "Daggu",
            "Dagu",
            "Daima",
            "Daku",
            "Dalakalari",
            "Dalori",
            "Dalwa",
            "Dam",
            "Damagum",
            "Damagun",
            "Damasak",
            "Damatura",
            "Damaturu",
            "Damboa",
            "Damboa district",
            "Dan Mayan",
            "Dananaca",
            "Darazo",
            "Darka",
            "Darmanti",
            "Dasa",
            "Dass",
            "Daura",
            "Deddere",
            "Degema",
            "Dikwa",
            "Dikwa district",
            "Dille",
            "Dingwai",
            "Dogon Daji",
            "Dogongona",
            "Dokshi",
            "Donga",
            "Doron Baga",
            "Dorowa",
            "Du",
            "Dukku",
            "Dum",
            "Dunukofia district",
            "Dusuman",
            "Egba",
            "Egbeda",
            "Egbema",
            "Egume",
            "Egwa",
            "Ekakpamre",
            "Eket",
            "Ekpoma",
            "Eku",
            "Eleme district",
            "Elepete",
            "Emi Dojo",
            "Emohua district",
            "Enerhen",
            "Enugu",
            "Enugu North district",
            "Enugu Ukwu",
            "Enugwu Ukwu",
            "Ererekri",
            "Escravos",
            "Escravos district",
            "Ethiope East district",
            "Etogi",
            "Ezza North district",
            "Fadagwai",
            "Fadama-Bona",
            "Fadan Karshe",
            "Fadan Karshi",
            "Fage",
            "Faljari",
            "Fang",
            "Festac",
            "Fika",
            "Fishdam",
            "Fonibiri",
            "Forcados",
            "Foron",
            "Foropa",
            "Foyi",
            "Fufore",
            "Fura Girke",
            "Gaambe-Tiev",
            "Gadaka",
            "Gadamayo",
            "Gafa",
            "Gafoni",
            "Gagdi",
            "Gaidamgari",
            "Gajiganna",
            "Gajiram",
            "Galga",
            "Gambaru",
            "Gamboru",
            "Gamboru Ngala",
            "Ganuwa",
            "Garawa",
            "Garki",
            "Garkida",
            "Garta",
            "Gashagar",
            "Gashua",
            "Gaskeri",
            "Gatamarwa",
            "Gatamwarwa",
            "Gaya",
            "Gazabu",
            "Gbaran-Ubie",
            "Gbeji",
            "Gbinde",
            "Geidam",
            "Gemana",
            "Ghumbili",
            "Ghwaa",
            "Gida Bua",
            "Gidan Adamu Mai-Akuya",
            "Gidan Dadi",
            "Gidan Dogo",
            "Gidan Idi",
            "Gidan Mutum Daya",
            "Gidan Sule",
            "Gidan Waya",
            "Gidan-Gambo",
            "Gidin Waya",
            "Giwa",
            "Godogodo",
            "Gogwada",
            "Golkofa",
            "Gomari",
            "Gombe",
            "Goniambari",
            "Goniri",
            "Gonori",
            "Gora",
            "Goron Dutse",
            "Gov",
            "Gubi",
            "Gubio",
            "Gubula",
            "Gudugum",
            "Gujba",
            "Gulak",
            "Gulani district",
            "Gulumba Gana",
            "Guma",
            "Gumsa",
            "Gumsuri",
            "Gumushi",
            "Gundumar Kasaya Labi",
            "Gundungyal",
            "Gur",
            "Gurguzu",
            "Gurkolle II",
            "Gurum",
            "Gusau",
            "Gwange",
            "Gwaram district",
            "Gwarama",
            "Gwargube",
            "Gwollam",
            "Gwoza",
            "Gwoza district",
            "Haipang",
            "Hambagda",
            "Hartsa",
            "Hausari",
            "Hawan Kibu",
            "Hawul district",
            "Heipang",
            "Hong",
            "Hotoro",
            "Hukke",
            "Humabza",
            "Huyum",
            "Ibadan",
            "Ibafo",
            "Ibeno",
            "Ibeno district",
            "Ibi",
            "Ido",
            "Ife",
            "Igabi district",
            "Igando",
            "Igbodu",
            "Igbokoda",
            "Igbuzor",
            "Igumale",
            "Ijan Ekiti",
            "Ikeala Ahiaba",
            "Iken",
            "Ikenegbu",
            "Ikorodu",
            "Ikorodu district",
            "Ikot Abasi",
            "Ikot Oko Osun",
            "Ilado",
            "Ile-Ido Ife",
            "Ilorin",
            "Ilutitun",
            "Imande Bebeshi",
            "Iordye",
            "Isoko North district",
            "Itas",
            "Itu",
            "Iwhrekan",
            "Iyanomo",
            "Izge",
            "Izghe",
            "Izige",
            "Jaji",
            "Jakana",
            "Jalango",
            "Jalingo",
            "Jamaare",
            "Jambutu",
            "Jere",
            "Jere district",
            "Jibu",
            "Jibwhiwhui",
            "Jiddari Polo",
            "Jilang",
            "Jol",
            "Jos",
            "Jos district",
            "Kabba",
            "Kabene-Surubu",
            "Kabrihu",
            "Kabuna",
            "Kaduna",
            "Kafanchan",
            "Kafin Hausa",
            "Kaga",
            "Kaigamari",
            "Kajola",
            "Kajuru",
            "Kaka",
            "Kakuruk",
            "Kala Balge",
            "Kala-Balge district",
            "Kalabalge district",
            "Kaleri",
            "Kallali",
            "Kamale",
            "Kambari",
            "Kamtahi",
            "Kamuya",
            "Kanamma",
            "Kangarwa",
            "Kaninkon",
            "Kano",
            "Kano-Kabawa",
            "Kanoyel",
            "Kanuyya",
            "Kara",
            "Karbutu",
            "Kardewa",
            "Kareto",
            "Karlahi",
            "Karnuwa",
            "Katamma",
            "Katarko",
            "Katsina",
            "Katsina Ala",
            "Kaumutayahi",
            "Kaura",
            "Kautikari",
            "Kautikiri",
            "Kautuva",
            "Kawuri",
            "Kaya",
            "Kayamla",
            "Keana district",
            "Keffi",
            "Keffin Hausa",
            "Kesa Kura",
            "Kesawa",
            "Keta",
            "Khana district",
            "Kijimatari",
            "Kiken",
            "Kimba",
            "Kirchiga",
            "Kirchinga",
            "Kirfi district",
            "Klaima",
            "Kodarko",
            "Kodomti",
            "Kodomun",
            "Kofa",
            "Kofar Gwari",
            "Kogoduk",
            "Kogom",
            "Koibe",
            "Kojoli",
            "Kokiya",
            "Kokori",
            "Kolere",
            "Kolori",
            "Komdi",
            "Komo",
            "Konduga",
            "Konduga district",
            "Kontagora",
            "Kopa",
            "Korokorosei",
            "Korongilum",
            "Kpansia",
            "Kpongbokiri",
            "Krenuwa",
            "Kuba",
            "Kubi",
            "Kubla",
            "Kuborshosho",
            "Kubu",
            "Kuburmbila",
            "Kuburmbula",
            "Kuburnvwu",
            "Kubuwa",
            "Kubwa district",
            "Kuda Kaya",
            "Kuje",
            "Kuka",
            "Kukawa",
            "Kukawa district",
            "Kukum Gida",
            "Kula",
            "Kulungu",
            "Kumala",
            "Kumbotso",
            "Kumbur",
            "Kumuya",
            "Kuru Karama",
            "Kurumin Dodo",
            "Kurutie",
            "Kuzen",
            "Kwajaffa",
            "Kwale",
            "Kwali",
            "Kwanar Dutse",
            "Kwangwami",
            "Kwashebe",
            "Kwatar Mali",
            "Kwatara",
            "Kwaya Kusar",
            "Kwaya Kusar district",
            "Kyado",
            "Kyankyashe",
            "Ladi Mbutaye",
            "Lafia",
            "Lagoa",
            "Lagos",
            "Lamba Gyambar",
            "Lapai",
            "Lassa",
            "Lawaru",
            "Lefu",
            "Lekki",
            "Liddle",
            "Ligali",
            "Liman Kara",
            "Limankara",
            "Lingis",
            "Linmakara",
            "Logbia",
            "Logo district",
            "Logomani",
            "Lokoja",
            "Longvel",
            "Luka",
            "Mada",
            "Madagali",
            "Madagali district",
            "Madakiya",
            "Madalla",
            "Maduwari",
            "Mafa",
            "Magar",
            "Maggar",
            "Magumeri",
            "Mai Gora",
            "Maiduguri",
            "Maiduguri district",
            "Maiduwa",
            "Maigora",
            "Maiha",
            "Maikadiri",
            "Maikatako",
            "Mainok",
            "Mairari",
            "Mairi",
            "Maiwa",
            "Makaraba",
            "Makintamari",
            "Makurdi",
            "Malali",
            "Malam Fatori",
            "Malari",
            "Mammanti",
            "Mamudo",
            "Manchok",
            "Mandirari",
            "Mangugum",
            "Manjita",
            "Marabar-Mubi",
            "Marama",
            "Marfunudi",
            "Markurdi",
            "Marte",
            "Marte district",
            "Mashemeri",
            "Mashimari",
            "Matangle",
            "Matube",
            "Mavo",
            "Mbanyagbe",
            "Mbatie",
            "Mbatoli district",
            "Meleri",
            "Meringa",
            "Mgbekpa",
            "Michika",
            "Midlu",
            "Mifa",
            "Mildu",
            "Minna",
            "Miringa",
            "Missini",
            "Mkovur",
            "Mobbar",
            "Molai",
            "Monguno",
            "Monguno district",
            "Mubeng",
            "Mubi",
            "Mule",
            "Mulehe",
            "Muna Delti",
            "Muna Gari",
            "Mussa",
            "Mussini",
            "Nabordo",
            "Nafada",
            "Namaran",
            "Nandu",
            "Nangere",
            "Nara",
            "Narsarawa",
            "Nawaje",
            "Nayi",
            "Nbishu",
            "Nchiha",
            "Ndokwa West district",
            "Ndongo",
            "Nembe",
            "Nembe district",
            "New Marte",
            "Ngala",
            "Ngala district",
            "Ngala district.",
            "Ngalda",
            "Ngamdu",
            "Ngelzarma",
            "Ngo",
            "Ngom",
            "Ngouroge",
            "Ngulde",
            "Nguro Soye",
            "Ngurojina",
            "Ngurosoya",
            "Ngurosoye",
            "Nguru Nguro",
            "Ngyo",
            "Nindem",
            "Ningon",
            "Njimtilo",
            "Noyine",
            "Nsit Ibom district",
            "Nsukka district",
            "Ntsiha",
            "Numan district",
            "Nwajurko",
            "Nyakoo",
            "Nyanya",
            "Nyibango",
            "Nzhwerivo",
            "Nzorov",
            "Obagi",
            "Obeagu",
            "Obi district",
            "Obio Usiere",
            "Obomkpa",
            "Obor",
            "Obosi",
            "Obrikom",
            "Odi",
            "Odimodi",
            "Ogba district",
            "Ogbagaji",
            "Ogbete",
            "Ogbia",
            "Ogbogwu",
            "Ogijo",
            "Oginbo",
            "Oguma",
            "Ogwule",
            "Ohanaeze Ndigbo",
            "Ohaukwu district",
            "Ohoro",
            "Oke Ako",
            "Okehi district",
            "Okene",
            "Okene district",
            "Oko-Asagun",
            "Okokolo",
            "Okololo",
            "Okon",
            "Okono",
            "Okoroete",
            "Okpanam",
            "Okpaya",
            "Okpokwu district",
            "Okrika",
            "Oku Iboku",
            "Okuokoko",
            "Oleh",
            "Ologba",
            "Olokorno",
            "Omala district",
            "Omi",
            "Omoku",
            "Omumah",
            "Onitsha",
            "Onitsha North district",
            "Onne",
            "Opume",
            "Orawua",
            "Ore",
            "Oredo district",
            "Orhuwhorun",
            "Orlu",
            "Oron",
            "Osara",
            "Ose district",
            "Osogbo",
            "Ossissa",
            "Ota",
            "Otu-Jeremi",
            "Otukpo-lgumale",
            "Ovia South-West district",
            "Owerri",
            "Owhrode",
            "Oye",
            "Pasakori",
            "Pela Birni",
            "Peremabiri",
            "Perigbene",
            "Port Harcourt",
            "Port Harcourt district",
            "Potiskum",
            "Pulka",
            "Pyakman",
            "Rann",
            "Rijiyar Zaki",
            "Rim",
            "Rimi",
            "Ringim",
            "Riyom",
            "Riyom district",
            "Ropp",
            "Ruk",
            "Rumuekini",
            "Rumurigo",
            "Sabon Gari",
            "Sabon Garin Hyanbula",
            "Sabon Garin Kimba",
            "Sabon Garin Yamdula",
            "Sabon Kasuawa",
            "Sabon Layin Galadima",
            "Sabon-Gari",
            "Sabongari",
            "Sade",
            "Safere",
            "Sagbama",
            "Saha",
            "Saminaka",
            "Sand fill",
            "Sanga district",
            "Sangana",
            "Sapele",
            "Sardauna district",
            "Sasawa",
            "Sebungen Ubosha",
            "Sengana",
            "Sha",
            "Shaausu",
            "Shaffa",
            "Shalomi Creek",
            "Shani",
            "Shawa",
            "Shetimari",
            "Sho",
            "Shonong",
            "Shuwa",
            "Shuwari Buri",
            "Simari",
            "Sokoto",
            "Song",
            "Southern Ijaw district",
            "Sulega",
            "Suleja",
            "Sumaila",
            "Suwasara",
            "Taagbe",
            "Taba",
            "Tafawa Balewa",
            "Takowok",
            "Tashan Alade",
            "Tashok",
            "Tella",
            "Tilden Fulani",
            "Tor Donga",
            "Toshia",
            "Totari",
            "Trans-Ekulu",
            "Tse Akenyi",
            "Tse Atakpa",
            "Tse Chia",
            "Tse Gusa",
            "Tse Gyudu",
            "Tse Ikyoor",
            "Tse Nhumbe",
            "Tse-Gbaun",
            "Tse-Igboughul",
            "Tsemue",
            "Tsilda",
            "Tswarev",
            "Tuba",
            "Tudun Wada",
            "Tula",
            "Tunyan",
            "Uba",
            "Ubuneke-Ivbiaro",
            "Udu district",
            "Ugbende Mue",
            "Ughelli",
            "Ughelli North district",
            "Ugondo",
            "Ukemberegya",
            "Ukpabi Nimbo",
            "Ukpo",
            "Ukula",
            "Ukum district",
            "Umarari",
            "Umarri",
            "Ummarari",
            "Umuahia",
            "Umuezekoha",
            "Unguwan Ganye",
            "Ungwan Dauda",
            "Ungwan Kwalla",
            "Ungwan Magaji",
            "Ungwan Rimi",
            "Ungwar Sarki",
            "Unknown",
            "Usor",
            "Utan Brama",
            "Utonkon",
            "Uyo",
            "Uzaagir",
            "Uzer",
            "Vaase",
            "Vande Ikya district",
            "Vat",
            "Ville",
            "Vimtim",
            "Waga",
            "Waga Mangoro",
            "Wajirko",
            "Wajiro",
            "Wala",
            "Walama",
            "Warabe",
            "Warawara",
            "Warri",
            "Warri North district",
            "Warri South district",
            "Warri South-West district",
            "Warri district",
            "Warsala",
            "Wasasa",
            "Wase",
            "Watu",
            "Wayo",
            "Wereng",
            "Wokilli",
            "Wonaka",
            "Woru",
            "Wukari",
            "Wukari district",
            "Wulgo",
            "Wulle",
            "Wumban",
            "Wumbi",
            "Wumyeduga",
            "Wunti Dada",
            "Yaffa",
            "Yakshari",
            "Yale",
            "Yamtage",
            "Yamteke",
            "Yana",
            "Yaza",
            "Yazza",
            "Yelwa",
            "Yenagoa",
            "Yenegoa district",
            "Yola",
            "Yola district",
            "Yunusari",
            "Zagan",
            "Zaki Biam",
            "Zakupang",
            "Zakupwang",
            "Zalau",
            "Zamadede",
            "Zambuk",
            "Zandyen",
            "Zangan Atakar",
            "Zangang",
            "Zange",
            "Zango",
            "Zango-Kataf",
            "Zar",
            "Zaria",
            "Zawan",
            "Zunburan",
            "Zurmi district",
        ]
        session.group_options = [
            "Ansaru (Jama'atu Ansarul Muslimina Fi Biladis Sudan)",
            "Bachama extremists",
            "Berom Militants",
            "Biafra Zionist Movement (BZM)",
            "Boko Haram",
            "Concerned Militant Leaders (CML)",
            "Council for Popular Justice",
            "Coup plotters",
            "Delta Democratic Militia",
            "Effiat ethnic roup or Jbibio Peoples",
            "Egbema National Front",
            "Egbesu Youths of the Bayelsa",
            "Fulani extremists",
            "Gang",
            "Gugama Youth Federation",
            "Gunmen",
            "Hauso Ethnic Group",
            "Ijaw extremists",
            "Indigenous People of Biafra (IPOB)",
            "Islamic Movement (Nigeria)",
            "Itsekiri",
            "Modakeke Ethnics",
            "Movement for the Actualization of the Sovereign State of Biafra (MASSOB)",
            "Movement for the Emancipation of the Niger Delta (MEND)",
            "Muslim extremists",
            "Muslims",
            "Niger Delta Avengers (NDA)",
            "Niger Delta Greenland Justice Mandate (NDGJM)",
            "Niger Delta Justice Defense Group (NDJDG)",
            "Niger Delta Liberation Force (NDLF)-Nigeria",
            "Niger Delta People's Volunteer Force (NDPVF)",
            "Niger Delta Vigilante (NDV)",
            "Niger Delta extremists",
            "Odua Peoples' Congress (OPC)",
            "People's Democratic Party (PDP)",
            "Red Scorpion",
            "Separatists",
            "Shia Muslim extremists",
            "Sunni Muslim extremists",
            "Tarok Militia",
            "The Joint Revolutionary Council",
            "Tiv Militia",
            "Unknown",
            "Urhobo Gbagbako",
            "Urhobo Revolutionary Army",
            "Zimbabwe Patriotic Front",
        ]
    else:
        session.city_options = ["NOT IMPLEMENTED"]
        session.group_options = ["NOT IMPLEMENTED"]


col1, col2, col3 = st.columns(3)
session.region_name = col1.selectbox(
    "Select Region: ",
    sorted(
        [
            "South Asia",
            "South America",
            "Eastern Europe",
            "Western Europe",
            "Sub-Saharan Africa",
            "Central America & Caribbean",
            "Middle East & North Africa",
            "Southeast Asia",
            "North America",
            "Australasia & Oceania",
            "Central Asia",
            "East Asia",
        ]
    ),
)

set_country_option(session.region_name)
session.country_name = col2.selectbox(
    "Select Country: ", sorted(session.country_options), help="Select region first",
)

set_city__group_option(session.country_name)
city = col3.selectbox(
    "Select City: ", sorted(session.city_options), help="Select country first"
)

duration_24hrs = col1.selectbox(
    "Is the attack duration greater than 24hrs?", ["Yes", "No"]
)
ismultiple = col2.selectbox(
    "Is the attack a single or multiple attack?", ["Single", "Multiple"]
)

attacktype = col3.selectbox(
    "Select the ataack type",
    sorted(
        [
            "Armed Assault",
            "Hostage Taking (Kidnapping)",
            "Assassination",
            "Bombing/Explosion",
            "Hijacking",
            "Unknown",
            "Facility/Infrastructure Attack",
            "Hostage Taking (Barricade Incident)",
            "Unarmed Assault",
        ]
    ),
)

targettype_name = col1.selectbox(
    "Select the target type",
    sorted(
        [
            "Private Citizens & Property",
            "Police",
            "Government (Diplomatic)",
            "Military",
            "Transportation",
            "Unknown",
            "Utilities",
            "Government (General)",
            "Violent Political Party",
            "Journalists & Media",
            "Business",
            "Terrorists/Non-State Militia",
            "NGO",
            "Educational Institution",
            "Religious Figures/Institutions",
            "Telecommunication",
            "Airports & Aircraft",
            "Maritime",
            "Abortion Related",
            "Other",
            "Tourists",
            "Food or Water Supply",
        ]
    ),
)
weapontype_name = col2.selectbox(
    "Select the weapon type",
    sorted(
        [
            "Firearms",
            "Explosives",
            "Unknown",
            "Incendiary",
            "Melee",
            "Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)",
            "Radiological",
            "Chemical",
            "Fake Weapons",
            "Sabotage Equipment",
            "Other",
            "Biological",
        ]
    ),
)
kid_is_hostage = col3.selectbox("Is a kid held hostage?", ["Yes", "No"])

group_name = col1.selectbox("What is the group name?", sorted(session.group_options),)


# Encode the selected values
df_pred = pd.DataFrame(
    [
        [
            session.region_name,
            session.country_name,
            city,
            duration_24hrs,
            ismultiple,
            attacktype,
            targettype_name,
            weapontype_name,
            kid_is_hostage,
            group_name,
        ]
    ],
    columns=[
        "region_name",
        "country_name",
        "city",
        "Duration>24hrs",
        "ismultiple",
        "attacktype",
        "targettype_name",
        "weapontype_name",
        "kid_is_hostage",
        "group_name",
    ],
)
df_pred["Duration>24hrs"] = df_pred["Duration>24hrs"].apply(lambda x: int(x == "Yes"))
df_pred["kid_is_hostage"] = df_pred["kid_is_hostage"].apply(lambda x: int(x == "Yes"))
df_pred["ismultiple"] = df_pred["ismultiple"].apply(lambda x: int(x == "Multiple"))

if st.button("Get Prediction"):
    # Make predictions using the loaded model
    prediction = model.predict_proba(df_pred)
    out_df = pd.DataFrame(prediction, columns=['Failed', 'Successful']).melt()
    out_df.columns = ["Category", "Probability"]
    
    chart = alt.Chart(out_df).mark_bar(size=50).encode(
        x= 'Category',
        y= 'Probability'
    ).properties(
        width=100,
        title='Probability of Success or Failure'
    )
    # Rendering the chart in Streamlit
    st.sidebar.altair_chart(chart, use_container_width=True)
